"""Add advanced card fields

Revision ID: b56638bb13fd
Revises: 31570da7d555
Create Date: 2026-03-02 03:44:16.956386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56638bb13fd'
down_revision: Union[str, None] = '31570da7d555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cards', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('cards', sa.Column('tags', sa.String(length=200), nullable=True))
    op.add_column('cards', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'assignee_id')
    op.drop_column('cards', 'tags')
    op.drop_column('cards', 'priority')
    op.drop_column('cards', 'due_date')
    # ### end Alembic commands ###
